### PR TITLE
feat: update Cypress tests with a new running strategy

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Port the logic from https://github.com/SwissDataScienceCenter/renku/pull/3150

After merging this PR, I will tag a new release and update the corresponding actions in the other Renku repositories.

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
Testing here https://github.com/SwissDataScienceCenter/renku-ui/pull/2676 and here https://github.com/SwissDataScienceCenter/renku-ui/pull/2677

**Review by leafty — APPROVED** [review]
LGTM 👍 thanks!

**Comment by leafty** [comment]
@lorenzo-cavazzi I noticed that this uses node v16, and not v18. I think we need to use the setup-node action before the cypress tests to ensure we always use the current node LTS

**Comment by lorenzo-cavazzi** [comment]
@leafty I guess staying with whatever is used by the cypress action isn't too bad. We can bump it to 18 if you think it's important #56

**Comment by leafty** [comment]
> @leafty I guess staying with whatever is used by the cypress action isn't too bad. We can bump it to 18 if you think it's important #56

Actually, it's the node version used by GitHub actions. The cypress action doesn't setup node.

**Pull request merged**
