### PR TITLE
chore: Update Helm in publish-chart to latest version.

### PR DESCRIPTION
**Pull request by aledegano**
This is required to correctly handle OCI Helm repositories.

### CODE REVIEW

**Review by rokroskar — COMMENTED** [review]
can't we use the same Dockerfile as in `deploy-renku`?

**Comment by rokroskar** [comment]
but the base images could be the same - then we avoid the problem that prompted this PR in the first place

**Comment by aledegano** [comment]
Maybe. But it's not really solving the problem because the versions of the base images will be independent so we might still forget about updating one of the two...

**Comment by rokroskar** [comment]
that's why this PR should also include a dependabot yaml file :) Though since @Panaetius already approved it I suppose you can merge, but we should probably do a follow up in short order

**Pull request merged**
